//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSV_Entity_Framwork_Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SV
    {
        public string MSSV { get; set; }
        public string Name { get; set; }
        public System.DateTime Date { get; set; }
        public string DiaChi { get; set; }
        public string tel { get; set; }
        public Nullable<int> Nien_Khoa { get; set; }
        public int ID_Lop { get; set; }
    
        public virtual Lop Lop { get; set; }
    }
}
