//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSV_Entity_Framework_Demo_Model_First
{
    using System;
    using System.Collections.Generic;
    
    public partial class sinhviendiachi
    {
        public int id { get; set; }
        public string diachi1 { get; set; }
        public string diachi2 { get; set; }
        public string thanhpho { get; set; }
    
        public virtual Sinhvien Sinhvien { get; set; }
    }
}
