<?xml version="1.0" encoding="utf-8"?><Database Name="QLSV" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ACER;Initial Catalog=QLSV;Integrated Security=True" SettingsObjectName="LINQ_Demo.Properties.Settings" SettingsPropertyName="QLSVConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.SV" Member="SVs">
    <Type Name="SV">
      <Column Name="MSSV" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="tel" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Nien_Khoa" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_Lop" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Lop_SV" Member="Lop" ThisKey="ID_Lop" OtherKey="ID_Lop" Type="Lop" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Lop" Member="Lops">
    <Type Name="Lop">
      <Column Name="ID_Lop" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Ten_Lop" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Lop_SV" Member="SVs" ThisKey="ID_Lop" OtherKey="ID_Lop" Type="SV" />
    </Type>
  </Table>
</Database>